mod.id = "openlink2"
mod.name = "OpenLink 2"
mod.group = "cn.scarefree"
mod.version = "0.1.0"
mod.channel_tag = "-alpha.1"
mod.description = "OpenLink 2!!!"
mod.authors = ["Star Carefree"]
mod.contributors = ["Terry_MC", "zirranYa"]
mod.inception_year = "2026"
mod.license.name = "MIT"
mod.license.url = "https://opensource.org/licenses/MIT"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/StarCarefree/OpenLink2"
mod.homepage_url = "https://github.com/StarCarefree/OpenLink2"
mod.issues_url = "https://github.com/StarCarefree/OpenLink2/issues"
mod.discord_url = ""
[[mod.pom.developers]]
id = "scarefree"
name = "Star Carefree"
url = "https://github.com/StarCarefree"

[fabric]
deps.fabric-loader = "0.19.2"

[fabric."1.18.2"]
deps.minecraft = "1.18.2"
deps.fabric-api = "0.77.0+1.18.2"
deps.modmenu = "3.2.5"

[fabric."1.19.2"]
deps.minecraft = "1.19.2"
deps.fabric-api = "0.77.0+1.19.2"
deps.modmenu = "4.2.0-beta.2"

[fabric."1.20.1"]
deps.minecraft = "1.20.1"
deps.fabric-api = "0.92.9+1.20.1"
deps.modmenu = "7.2.2"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.modmenu = "15.0.0"

[fabric."26.1.2"]
deps.minecraft = "26.1.2"
deps.fabric-api = "0.146.1+26.1.2"
deps.modmenu = "18.0.0-alpha.8"
publish.additionalVersions = ["26.1.1", "26.1"]

[forge]

[forge."1.18.2"]
deps.minecraft = "1.18.2"
deps.forge = "40.3.0"
deps.apricityui = "1.0.1"
deps.apricityuimrvid = "QBKfDvnC"

[forge."1.19.2"]
deps.minecraft = "1.19.2"
deps.forge = "43.5.2"
deps.apricityui = "1.0.1"
deps.apricityuimrvid = "ptoak7gK"

[forge."1.20.1"]
deps.minecraft = "1.20.1"
deps.forge = "47.4.10"
deps.apricityui = "1.1.6-dev"
deps.apricityuimrvid = "p2jC070U"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"
deps.apricityui = "1.1.3-dev"
deps.apricityuimrvid = "YU2KD9rG"

[neoforge."26.1.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.1.2.29-beta"
deps.apricityui = "1.1.3-dev"
deps.apricityuimrvid = "SN4xKGNu"
publish.additionalVersions = ["26.1.1", "26.1"]
